unique_ids:
  assets:
    standard-page.html: CRUWLH2W253SFH4QJPL7O2IOFHQLFRE5
    theme.css: HJOP7Y4OFCJ5SVYNKEIIX5IRD63HCFOM
  forms:
    Form1: RETLODYWRRHJLE6KX5MLXTBTRK2TFL7K
  modules: {}
  scripts: {}
  server_modules: {}
